version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    ports: 
      - 9000:9000
      - 9001:9001
    volumes:
      - s3:/data
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      
  mongo:
    image: mongo:4.4
    volumes:
      - mongodb:/data/db
    ports: []
      # - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=coordinator
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

  redis:
    image: redis
    ports: []
      # - "6379:6379"
    
  coordinator-node:
    build:
      context: .
      target: any-sync-coordinator
    ports:
      - "4830:4830"
    restart: unless-stopped
    volumes:
      - ./configurations/coordinator.yml:/etc/anytype/coordinator.yml

  sync-node:
    build:
      context: .
      target: any-sync-node
    ports:
      - "4430:4430"
    restart: unless-stopped
    volumes:
      - ./configurations/sync_1.yml:/etc/anytype/sync_1.yml

  file-node:
    build:
      context: .
      target: any-sync-filenode
    ports:
      - "4730:4730"
    restart: unless-stopped
    volumes:
      - ./configurations/file_1.yml:/etc/anytype/file_1.yml

volumes:
  s3:
  mongodb:
